### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by 3dot141** [mugiwara85/CodeblockCustomizer#54]
i encountered problem like [this link](https://forum.obsidian.md/t/obsidian-moves-so-slow-when-i-drag-it-with-my-mouse/34973)

when i drag file or heading, the move will very slow.

after i use chrome devtools to debug,
in `style.css`，i found some code which will cause some performance issues in Obisidian's some actions 
```
body:not(:not([class*='codeblock-customizer-show-langnames'])) .codeblock-customizer-header-text,
body:not(:not([class*='codeblock-customizer-show-langicons'])) .codeblock-customizer-header-container-specific:has(.codeblock-customizer-icon) .codeblock-customizer-header-text,
body:not(:not([class*='codeblock-customizer-header-collapse-command'])):not(:not([class*='codeblock-customizer-show-langnames-always'])) .codeblock-customizer-header-container:has([class^="codeblock-customizer-header-language-tag-"]) .codeblock-customizer-header-text,
body:not(:not([class*='codeblock-customizer-header-collapse-command'])):not(:not([class*='codeblock-customizer-show-langicons-always'])) .codeblock-customizer-header-container:has(.codeblock-customizer-icon) .codeblock-customizer-header-text {
  padding-left: 0px;
}
```

i think this css selector is too complex, and will cause render html slower.

Can anyone reproduce this issue and rectify it?

i upload one movie that display this problem
https://github.com/mugiwara85/CodeblockCustomizer/assets/19152476/4ff6a715-34e0-4699-9213-4bbfdefa372a

**Comment by mugiwara85** [comment]
Unfortunately, I can't reproduce it. Could you try disabling all plugins, and then check? After that you could try to enable your plugins one by one. Maybe we get a little closer to what causes this?

**Comment by 3dot141** [comment]
i try again, and find another condition which is use other themes like minimal.
this is my reproduce steps:
1. open sandbox vault
2. install new theme like minimal
3. install codeblock customizer
4. try to drag heading or file and reproduce it

sandbox vault only has 1 theme and 1 community plugin which is codeblock custimizer.
i try to only install  other theme like lts, and not install plugin. the drag is normal.

**Comment by mugiwara85** [comment]
Ok, I can reproduce it now. I will look at it, what could be the problem.

**Comment by mugiwara85** [comment]
This will be fixed in the next release. If you want you can test it now. You just have to replace the styles.css file manually. Maybe you find anything else.

**Comment by 3dot141** [comment]
i try it, the issue is resolved, thanks

**Comment by 6StringSam** [comment]
I'm having the same issue.  Replace the styles.css file with what?  A blank file?

**Comment by mugiwara85** [comment]
@6StringSam Why would you replace the styles.css file with a blank file? It was meant to replace the styles.css file with the current styles.css file, which was not yet released. But what is your problem exactly? Show a video, or describe in detail maybe? Did you try anything to narrow down the problem? Create a new Vault, install the plugin, and try out if the problem still exists. If not, then the problem is caused probably by another plugin. Try adding your plugins one by one, to narrow it down when the problem appears. Do you have custom CSS applied? If yes, try disabling it. Does the problem only occur if a specific theme is used? Also, this issue was opened and closed almost a year ago. Just open a new issue.

**Comment by 6StringSam** [comment]
I'm experiencing the slowness dragging files.  The problem persists with every other plug-in disabled and it my test vault as well.  Replacing the style.css with a black file fixed the flow file/folder dragging issue.  

How do I get a copy of the new "unreleased" styles.css file?

**Comment by mugiwara85** [comment]
> I'm experiencing the slowness dragging files. The problem persists with every other plug-in disabled and it my test vault as well. Replacing the style.css with a black file fixed the flow file/folder dragging issue.
> 
> How do I get a copy of the new "unreleased" styles.css file?

You are replying to an issue which was solved almost a year ago! There is no unreleased styles.css. There was one a year ago, when this issue was opened! Open a new issue!
